development:
  secret_key_base: {secret_key}
  ZD_URL: https://{your_subdomain}.zendesk.com/api/v2/
  ZD_USERNAME: you@example.com
  ZD_PASSWORD: your_pw

test:
  secret_key_base: {secret_key}
  ZD_URL: https://{your_subdomain}.zendesk.com/api/v2/
  ZD_USERNAME: you@example.com
  ZD_PASSWORD: your_pw

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ZD_URL: https://{your_subdomain}.zendesk.com/api/v2/
  ZD_USERNAME: you@example.com
  ZD_PASSWORD: your_pw
